### ISSUE TITLE
The search input should be visible on a search page.

### ISSUE THREAD

**Issue by mitogh** [moxienyc/WordPress-Wiki#10]

**Comment by jrrrsmith** [comment]
@mitogh do you mean anothe search input besides the one activated by the spyglass link in the header?

**Comment by mitogh** [comment]
For example if you go to this page: 

http://wiki.getmoxied.net/?s=wordpress 

the search input it's closed, try to search something and then hit enter the new page needs to have open the search input. 

Video: http://snaps.getmoxied.net/2W3D402F3R2e

Also we need to add a better color for the input text. 

Thank you @jrrrsmith

**Comment by mitogh** [comment]
This has been fixed on 861ee1b
