### ISSUE TITLE
Create a more fluid layout in larger sizes.

### ISSUE THREAD

**Issue by mitogh** [moxienyc/WordPress-Wiki#12]
Increase the size of columns in larger screen sizes for example: 

![screen shot 2015-08-05 at 14 42 20](https://cloud.githubusercontent.com/assets/3921289/9096032/52dbc58c-3b80-11e5-9815-aa56a581813b.png)
![screen shot 2015-08-05 at 14 42 45](https://cloud.githubusercontent.com/assets/3921289/9096033/52f2d9ac-3b80-11e5-963b-0d8d24dfb006.png)

Please refer to http://wwwhere.io/ to have an example about how it should work.

**Comment by jrrrsmith** [comment]
@mitogh @wissambellali ready for QA

**Comment by mitogh** [comment]
Looks good to me @jrrrsmith I will close this issue. 

cc @wissambellali
